import Head from 'next/head'
import 'tailwindcss/tailwind.css'

import Navbar from '../components/Navbar'
import Main from '../components/Main'
import About from '../components/About'
import Tech from '../components/Tech'
import Contact from '../components/Contact'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Devesh B</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <Main />
      <About /> 
      <Tech />
      <Contact />

      <footer>
        <div className="text-center p-4 mt-4">
            My <a className="text-blue-500 border-b border-transparent hover:border-blue-500" href="https://drive.google.com/file/d/1MozSYw-itCtqPn2p8ysRA3G_30bTZAz-/view?usp=sharing" rel="noreferrer" target="_blank">Resume</a>
          </div>
      </footer>
      
    </div>
  )
}
